### PR TITLE
Update segmentation template

### PR DESCRIPTION
**Pull request by tmieslinger**
* update dropsonde info
* add takeoff and landing
* add plot showing segment
* add functionality to save the segment info to YAML

### CODE REVIEW

**Review by reredl — COMMENTED** [review]
A bit difficult to review a note by just looking at the code changes. I downloaded the three files and copied it into the main branch of my public clone. When running the notebook the get_sondes_l1 function is not able to access the  latest.orcestra-campaign.org/products/HALO/dropsondes/Level_1/HALO-20240813a file, even though I can see the file in the browser. Any idea what is still missing?

**Comment by Lucalino** [comment]
The notebook adaptation and additions to the utils file look good to me. Thank you for implementing all these new features!
It would be great if this part of the pull request could be merged soon so that others can start using the new template. 
The only thing I'm not sure about is that the commit also contains the updated yaml and this one should only be merged after the review, right? Can you split the two parts and only merge the template? 🤔 ... also, I think the 'comments' field is missing in the yaml. Otherwise, the updated structure of the yaml file also looks good to me.

**Comment by tmieslinger** [comment]
@reredl could you check whether you used the latest [environment](https://github.com/orcestra-campaign/flight_segmentation/blob/main/scripts/environment.yaml) with `ipfsspec>=0.5.3`? I think you need at least `0.5.2` to be able to list the files as Level 1 dorpsonde data comes in many nc files.

**Comment by Lucalino** [comment]
I've checked your latest changes and recommend to merge this pull request. Many tanks for this improvement! I look forward to using the new template and think, it will speed up the segmentation significantly.

**Pull request merged**
